### ISSUE TITLE
pip install fails due to conflicts

### ISSUE THREAD

**Issue by tobiasgrossmann** [Azure/aistudio-copilot-sample#103]
I verified this with a clean new docker image and a local venv. 

`
INFO: pip is still looking at multiple versions of azureml-dataprep to determine which version is compatible with other requirements. This could take a while.
  Using cached azureml_dataprep-4.14.0-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.10-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.9-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.8-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.7-py3-none-any.whl.metadata (2.1 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached azureml_dataprep-4.12.6-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.5-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.4-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.2-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.1-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.0-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.7-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.6-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.5-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.4-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.3-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.2-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.1-py3-none-any.whl.metadata (2.1 kB)
ERROR: Cannot install azureml-dataprep because these package versions have conflicting dependencies.

The conflict is caused by:
    azureml-dataprep 5.1.6 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.5 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.4 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.3 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.2 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.1 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.0 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.0.0 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 4.14.0 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.10 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.9 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.8 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.7 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.6 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.5 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.4 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.2 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.1 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.0 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.7 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.6 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.5 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.4 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.3 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.2 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.1 depends on dotnetcore2<4.0.0 and >=3.0.0
`

pip --version
pip 24.0 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)

**Comment by luigiw** [comment]
@tobiasgrossmann can you share steps I can use to repro this error?

**Comment by tobiasgrossmann** [comment]
Sure:
```
git clone
docker build . 
```

**Comment by soderlind** [comment]
I'm getting (almost?) the same error following **Step 1b** in the README. I'm on a Mac.


Did: 
```
git clone https://github.com/azure/aistudio-copilot-sample
cd aistudio-copilot-sample
python3.11 -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt

```

Error log:

```
INFO: pip is looking at multiple versions of azureml-dataprep to determine which version is compatible with other requirements. This could take a while.
Collecting azureml-dataprep>4.11 (from azureml-dataprep[parquet]>4.11; extra == "index"->azure-ai-generative@ https://pkgs.dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_packaging/3572dbf9-b5ef-433b-9137-fc4d7768e7cc/pypi/download/azure-ai-generative/1a20240207004/azure_ai_generative-1.0.0a20240207004-py3-none-any.whl->azure-ai-generative[evaluate,index,promptflow]@ https://pkgs.dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_packaging/3572dbf9-b5ef-433b-9137-fc4d7768e7cc/pypi/download/azure-ai-generative/1a20240207004/azure_ai_generative-1.0.0a20240207004-py3-none-any.whl->-r requirements.txt (line 7))
  Using cached azureml_dataprep-5.1.5-py3-none-any.whl.metadata (2.2 kB)
  Using cached azureml_dataprep-5.1.4-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-5.1.3-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-5.1.2-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-5.1.1-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-5.1.0-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-5.0.0-py3-none-any.whl.metadata (2.1 kB)
INFO: pip is still looking at multiple versions of azureml-dataprep to determine which version is compatible with other requirements. This could take a while.
  Using cached azureml_dataprep-4.14.0-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.10-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.9-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.8-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.7-py3-none-any.whl.metadata (2.1 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached azureml_dataprep-4.12.6-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.5-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.4-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.2-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.1-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.12.0-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.7-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.6-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.5-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.4-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.3-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.2-py3-none-any.whl.metadata (2.1 kB)
  Using cached azureml_dataprep-4.11.1-py3-none-any.whl.metadata (2.1 kB)
ERROR: Cannot install azureml-dataprep because these package versions have conflicting dependencies.

The conflict is caused by:
    azureml-dataprep 5.1.6 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.5 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.4 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.3 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.2 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.1 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.1.0 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 5.0.0 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep 4.14.0 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.10 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.9 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.8 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.7 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.6 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.5 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.4 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.2 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.1 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.12.0 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.7 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.6 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.5 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.4 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.3 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.2 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep 4.11.1 depends on dotnetcore2<4.0.0 and >=3.0.0

```

**Comment by luigiw** [comment]
I can't repro this from my side somehow, the only difference I see is that I'm using pip version 23.2.1, I'll try pip 24.0 later today.

**Comment by soderlind** [comment]
@luigiw Using pip 23.2.1 I'm getting the error below, maybe because I'm om a M1 Pro (arm)?

Did:

```
git clone https://github.com/azure/aistudio-copilot-sample
cd aistudio-copilot-sample
python3.11 -m venv .venv
source .venv/bin/activate
pip install pip==23.2.1
pip install -r requirements.txt
```

```
  Downloading azureml_dataprep-4.11.1-py3-none-any.whl.metadata (2.1 kB)
ERROR: Cannot install azureml-dataprep[parquet]==4.11.1, azureml-dataprep[parquet]==4.11.2, azureml-dataprep[parquet]==4.11.3, azureml-dataprep[parquet]==4.11.4, azureml-dataprep[parquet]==4.11.5, azureml-dataprep[parquet]==4.11.6, azureml-dataprep[parquet]==4.11.7, azureml-dataprep[parquet]==4.12.0, azureml-dataprep[parquet]==4.12.1, azureml-dataprep[parquet]==4.12.10, azureml-dataprep[parquet]==4.12.2, azureml-dataprep[parquet]==4.12.4, azureml-dataprep[parquet]==4.12.5, azureml-dataprep[parquet]==4.12.6, azureml-dataprep[parquet]==4.12.7, azureml-dataprep[parquet]==4.12.8, azureml-dataprep[parquet]==4.12.9, azureml-dataprep[parquet]==4.14.0, azureml-dataprep[parquet]==5.0.0, azureml-dataprep[parquet]==5.1.0, azureml-dataprep[parquet]==5.1.1, azureml-dataprep[parquet]==5.1.2, azureml-dataprep[parquet]==5.1.3, azureml-dataprep[parquet]==5.1.4, azureml-dataprep[parquet]==5.1.5 and azureml-dataprep[parquet]==5.1.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    azureml-dataprep[parquet] 5.1.6 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep[parquet] 5.1.5 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep[parquet] 5.1.4 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep[parquet] 5.1.3 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep[parquet] 5.1.2 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep[parquet] 5.1.1 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep[parquet] 5.1.0 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep[parquet] 5.0.0 depends on azureml-dataprep-native<42.0.0 and >=41.0.0
    azureml-dataprep[parquet] 4.14.0 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.12.10 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.12.9 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.12.8 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.12.7 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.12.6 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.12.5 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.12.4 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.12.2 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.12.1 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.12.0 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.11.7 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.11.6 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.11.5 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.11.4 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.11.3 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.11.2 depends on dotnetcore2<4.0.0 and >=3.0.0
    azureml-dataprep[parquet] 4.11.1 depends on dotnetcore2<4.0.0 and >=3.0.0
``

**Comment by luigiw** [comment]
Hello @soderlind , thx for checking, m1 arm cpu can very well play a role here. I'm also using a m1 mac but I installed the x86 version of conda, is that an option for you?

**Comment by soderlind** [comment]
Thank you, @luigiw, the following worked:

First, installed [Miniconda3 macOS Intel x86 64-bit pkg](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.pkg) 

then:

```
git clone https://github.com/azure/aistudio-copilot-sample
cd aistudio-copilot-sample
conda create --name .venv python=3.11
conda activate .venv
pip install -r requirements.txt
```

**Comment by gercograndia** [comment]
Have the exact same problem, but in my case `conda` does not resolve it for me.

Using python 3.11.8, these steps reproduce it:

```console
conda create --name .venv python=3.11
conda activate .venv
pip install -r requirements.txt
```
Resulting in the same error:

```console
ERROR: Cannot install azureml-dataprep because these package versions have conflicting dependencies.
```

**Comment by soderlind** [comment]
@gercograndia, are you running the x86 or arm version of conda?

**Comment by jogradial** [comment]
Running into the same issues as @gercograndia on a arm64 machine

**Comment by gercograndia** [comment]
Sorry for the late response, but arm64 indeed. M2.

**Comment by soderlind** [comment]
@jogradial and @gercograndia, I'm also on an arm, but I installed, per @luigiw suggestion, the x86 version of conda. ([Miniconda3 macOS Intel x86 64-bit pkg](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.pkg))
