### ISSUE TITLE
ai: command not found

### ISSUE THREAD

**Issue by tomas-gajarsky** [Azure/aistudio-copilot-sample#58]
First of all, thanks for the promising Azure AI Studio preview!

I followed all the instructions in the README for setting up the local development environment as the GitHub Codespace never stopped loading. I successfully installed the requirements and the Azure CLI, but when I run `ai init` the `ai: command is not found` error is thrown. I have tried to set-up the local environment both in a virtual Python environment and a Python Docker image, but the outcome is the same. Below are some versions of installed tools and a warning I noticed during installation of the requirements that will hopefully be useful for debugging this issue.

**Python version**
Python 3.9.18

**CLI version**
azure-cli                         2.54.0

**Package versions**
azure-ai-generative          1.0.0b1
azure-ai-ml                  1.12.0
azure-ai-resources           1.0.0b1

**Warning when installing the requirements with pip**
` Using cached azure_ai_generative-0.0.0b1-py3-none-any.whl (1.2 kB)
WARNING: azure-ai-generative 0.0.0b1 does not provide the extra 'evaluate'
WARNING: azure-ai-generative 0.0.0b1 does not provide the extra 'index'
WARNING: azure-ai-generative 0.0.0b1 does not provide the extra 'promptflow'
`

**Comment by robch** [comment]
Hi @tomas-gajarsky,

Sorry you're experiencing problems getting the AI CLI installed and functioning. To help, I have a few questions to ask, related to your following "all the instructions in the README for setting up the local development environment:

(1) If you're installing on Linux, did you issue this command from the README?
     `curl -sL https://aka.ms/InstallAzureAICLIDeb | bash`

(2) If you did, what output did that show? It should look like this:
![image](https://github.com/Azure/aistudio-copilot-sample/assets/1608910/1b9316f7-9c73-4700-a0fd-5506455ad383)

(3) If you're installing on Windows or Mac, did you issue this command from the [doc instructions?](https://aka.ms/aistudio/docs/cli)
     `dotnet tool install --prerelease --global Azure.AI.CLI`

(4) If you did, what output did that show? It should look similar to the output from # 2

**Comment by tomas-gajarsky** [comment]
Hi @robch,

The original problem I had was my fault, apologies for that. I was installing the Azure CLI instead of Azure AI CLI as I missed AI in the installation command. However, now that I am trying to install Azure **AI** CLI when building a **Linux Docker image** by running:
`curl -sL https://aka.ms/InstallAzureCLIDeb | bash`

I am getting this message:
`Cannot determine the user to install the Azure.AI.CLI dotnet tool for`

The logic for selecting the user in the installation script seems to not support the Docker case with root user, but without the `SUDO_USER` environment variable. Let me know if you are planning to support Docker users and whether I should rename this issue.

**Comment by robch** [comment]
Thanks @tomas, Yes, let's start a new issue on that new topic. I'll also log it internally and get it prioritized.

**Comment by tomas** [comment]
@robch Please stop mentioning me in this repo.
