### ISSUE TITLE
The AI INIT command fails right at the beginning.

### ISSUE THREAD

**Issue by Arturo-Quiroga-MSFT** [Azure/aistudio-copilot-sample#60]
Hello, I am trying to install the sample, I am using a macOS machine, latest OS version (SONOMA), the virtual env I am using is for python 3.11.5..... for installing the Azure AI CLI I followed the macOS installation option using DOTNET 7.

When I type AI INIT, I do not get asked to login to Azure as the documentation indicates, I get shown options for Project or Standalone deployments. Regardless of the option I choose, I get the error below

<img width="1095" alt="Screenshot 2023-11-24 at 3 33 14 PM" src="https://github.com/Azure/aistudio-copilot-sample/assets/32229456/352dc98b-9ca2-4297-8d47-79f8d523c685">

Any ideas?.

Thanks

**Comment by Arturo-Quiroga-MSFT** [comment]
Attached  are the contents of the LOG file created after the error

[log-133448816437819960.log](https://github.com/Azure/aistudio-copilot-sample/files/13462076/log-133448816437819960.log)

**Comment by robch** [comment]
Thanks, Arturo, for the issue/report. The version of the CLI you are running is at least 3 weeks old, and at least 1 week prior to the Ignite conference/release. Please upgrade to the latest version of the `ai` CLI and let us know if you still have problems.

**Comment by Arturo-Quiroga-MSFT** [comment]
[like]  Arturo Quiroga reacted to your message:
________________________________
