### ISSUE TITLE
curl -sL https://aka.ms/InstallAzureAICLIDeb | sudo bash command failing. 

### ISSUE THREAD

**Issue by safdar23** [Azure/aistudio-copilot-sample#61]
hi, i am getting the below error while installing the AI CLI

/tmp/386b586f-d397-4ad7-bf53-3e98d5d33608/restore.csproj : error NU1202: Package Azure.AI.CLI 1.0.0-preview-20231116.1 is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / any. Package Azure.AI.CLI 1.0.0-preview-20231116.1 supports: net7.0 (.NETCoreApp,Version=v7.0) / any
The tool package could not be restored.
Tool 'azure.ai.cli' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by robch** [comment]
Hi @safdar23, There's an issue with our installation script that isn't properly checking the version of dotnet that's installed before trying to install dotnet 7. It only checks for the existence of dotnet, not specifically for dotnet 7. 

The work around for now is for you to install dotnet 7 SDK manually. Please follow these [instructions](https://dotnet.microsoft.com/en-us/download/dotnet/7.0), and then try installing the `ai` CLI again. 

![image](https://github.com/Azure/aistudio-copilot-sample/assets/1608910/0bc5b93b-eaf9-4015-b9cb-79cf70d9d6fb)

**Comment by tomas-gajarsky** [comment]
I'm writing to inquire about the ongoing issue with the installation script, which does not properly check for dotnet 7 before attempting the installation. This problem persists and affects the installation process.

Is there a timeline for when this issue will be addressed? Additionally, considering the manual installation of dotnet 7 SDK is cumbersome, it would be beneficial if this step could be integrated into the provided development container setup. Please let us know if this is being considered.

Thanks for the update in advance.
