### ISSUE TITLE
Semantic Kernel: AttributeError during plan execution

### ISSUE THREAD

**Issue by HenriSchulte-MS** [Azure/aistudio-copilot-sample#62]
When executing the copilot sample with semantic kernel implementation, plan execution always seems to encounter an error, [when the kernel attempts to generate a description for the function](
https://github.com/microsoft/semantic-kernel/blob/main/python/semantic_kernel/kernel.py#L308). The result from the plan execution includes `last_error_description:
"'NoneType' object has no attribute 'describe'"`.

This can be circumvented by executing the plan with `plan.invoke_async()` as opposed to `kernel.run_async(plan)`.
I have not yet been able to determine the exact root cause.

I am running Semantic Kernel version 0.3.15.dev0. Have not yet tested with 0.4 due to dependency conflicts.

**Comment by luigiw** [comment]
SK code is removed from this repo and will be moved to this repo, https://github.com/Azure-Samples/aistudio-python-semantickernel-sample/tree/main
