### ISSUE TITLE
ai init says no deployable models found

### ISSUE THREAD

**Issue by siegfried01** [Azure/aistudio-copilot-sample#66]
I'm trying to follow these directions: https://github.com/azure/aistudio-copilot-sample/tree/main#step-2-create-and-connect-to-azure-resources

I run "ai init" and it always fails with "*** No deployable models found *** CANCELED: No deployment selected".

**Comment by robertzk** [comment]
I had the same issue, please @ mention me if you were able to find a solution.

**Comment by qubitron** [comment]
You may not have quota available in the region you selected, please check the Manage -> Quota tab in Azure AI Studio to see what regions you have available quota in. We're working on improving the error messaging in the CLI for this case.

**Comment by alexsmithMSFT** [comment]
Same issue here...

```
> ai init
Subscription: REDACTED
                                                                  
AZURE AI PROJECT                                                  
Name: alexsmit-epic-navy-yak-ai-aiproj (eastus2)                  
                                                                  
AZURE OPENAI DEPLOYMENT (CHAT)                                    
Name: (Create new)                                                
                                                                  
CREATE DEPLOYMENT (CHAT)                                          
Model: *** No deployable models found ***                         
CANCELED: No deployment selected   
```

Creating Open AI resource via portal results in-
<img width="533" alt="image" src="https://github.com/Azure/aistudio-copilot-sample/assets/26260056/b89eef68-21b5-460a-92b4-846d4b33652c">
