### ISSUE TITLE
Running with semantickernel produces no real output

### ISSUE THREAD

**Issue by jhakulin** [Azure/aistudio-copilot-sample#76]
When I try semantickernel implementation as below:

`python src/run.py --implementation semantickernel --question "what is the waterproof rating of the tent I just ordered?"`

I get output:
`{'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': ''}, 'context': ''}]}`

Probably some extra configuration is needed for semantickernel to work? I followed the instructions in Step 4 in this sample document.

**Comment by luigiw** [comment]
SK code in this repo is out of date and will be removed from this repo.
