### ISSUE TITLE
AI Search index fails

### ISSUE THREAD

**Issue by jimmyshah83** [Azure/aistudio-copilot-sample#79]
Running the ai search index command fails with below error:

Command: ai search index update --files "./data/3-product-info/*.md" --index-name "product-info"

Error: 

Updating search index 'product-info' ...
  WARNING: Unhandled exception in Python script!

    ERROR: Python script failed! (exit code=1)

   OUTPUT: argument of type 'NoneType' is not iterable

**Comment by luigiw** [comment]
@jimmyshah83, we've updated the repo with new steps and python packages. Can you try again?
