### ISSUE TITLE
"ai init" fails while creating Azure AI resource

### ISSUE THREAD

**Issue by TSchmiedlechner** [Azure/aistudio-copilot-sample#8]
Hi everyone, first of all: thanks for the chance to participate in this preview! Super exciting to see what's going on here. 🙂 

Unfortunately, I run into a problem when following the _getting started_ guide, both in the provided Codespaces env and locally:
While the first steps are successful, the tool fails during creating the Azure AI resource, displaying the following error:

```
CREATE AZURE AI RESOURCE           
Group: rg-openai-dev-eastus2-tsc-demo (eastus2)                    
Name: aihub-dev-eastus2-tsc-demo001 
*** CREATING ***  ERROR: Python script failed! (exit code=1)
                                    
                                    
  OUTPUT:

      Class WorkspaceHub: This is an experimental class, and may change at any time. Please see https://aka.ms/azuremlexperimental for more information.
      Method workspace_hubs: This is an experimental method, and may change at any time. Please see https://aka.ms/azuremlexperimental for more information.
      Traceback (most recent call last):
        File "/tmp/tmpPZCD2l.tmp.py", line 55, in <module>
          main()
        File "/tmp/tmpPZCD2l.tmp.py", line 48, in main
          hub = create_hub(subscription_id, resource_group_name, resource_name, location, display_name, description)
        File "/tmp/tmpPZCD2l.tmp.py", line 27, in create_hub
          result = ml_client.workspace_hubs.begin_create(wshub).result()
        File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
          return func(*args, **kwargs)
      TypeError: WorkspaceHubOperations.begin_create() takes 1 positional argument but 2 were given
```

I've tried starting from scratch with a set of completely new resources, but experience the same issue ultimately. Is anyone else running into this? Any ideas how to solve this? Please let me know in case you need more information, obviously.

**Comment by qubitron** [comment]
Hi folks, this issue should now be resolved, can you please try again with the latest?

**Comment by bduric** [comment]
Hi all. Thanks for sharing this repo. I did manage to install majority  if not all services with ai init but the 
AZURE OPENAI DEPLOYMENT (CHAT)
Name: (Create new)

CREATE DEPLOYMENT (CHAT)
Model: *** No deployable models found ***
CANCELED: No deployment selected

How would I go about this fail. Is there a way to do it manually in AZURE AI Studio. or simply re-run ai init?
Thank you

**Comment by anjugds** [comment]
Hi all, Even I got the same issue as above.

AZURE AI RESOURCE
Name: test_ai_res (swedencentral)

CREATE AZURE AI PROJECT
Name: test-aistudio-pj3
*** CREATED ***  

AZURE OPENAI DEPLOYMENT (CHAT)
Name: (Create new)

CREATE DEPLOYMENT (CHAT)
Model: *** No deployable models found ***
CANCELED: No deployment selected

**Comment by dionoid** [comment]
Got the same issue in WestEurope region:
```
AZURE OPENAI DEPLOYMENT (CHAT)
Name: (Create new)

CREATE DEPLOYMENT (CHAT)
Model: *** No deployable models found ***
CANCELED: No deployment selected
```

When trying in East US region, I got a different error:
```
CREATE AZURE OPENAI RESOURCE
Region: eastus
Group: my-name-eager-weasel-rg
Kind: AIServices
Name: my-name-eager-weasel-ais
ERROR: Creating Cognitive Services resource: ERROR: argument --sku: expected one argument
```

**Comment by csnarain** [comment]
I'm getting a different error (see below) while doing ai init. Has anyone encountered this before? Pls help.

AI INIT

  Initializes (creates, selects, or attaches to) AI Projects and services.

  Choose between initializing:
  - AI Project: Recommended when using Azure AI Studio and/or connecting to multiple AI services.
  - Standalone resources: Recommended when building simple solutions connecting to a single AI service.

Initialize: New AI Project
Subscription: ****

AZURE AI RESOURCE
Name: (Create w/ integrated Open AI + AI Services)

CREATE AZURE AI RESOURCE
Region: Central US (centralus)
Group: (Create new)

CREATE RESOURCE GROUP
Region: Central US (centralus)
Name: genai-sandbox
*** CREATED ***

CREATE AZURE AI RESOURCE
Name: ****
*** CREATING ***  ERROR: Object reference not set to an instance of an object.

**Comment by rbalebako** [comment]
I have a similar problem.  When I run 
% ai init 
the workflow completes without asking for a search resource.  
It requests the following:
AZURE OPENAI RESOURCE
AZURE OPENAI DEPLOYMENT (CHAT)
at which point it lists the config and exits the workflow without any errors or warnings.

No config.json exists.
No search resource is prompted for or created.

I've followed the whole tutorial from scratch twice.   Can anyone help with either 1.) reasons why ai init exits without requesting a SEARCH RESOURCE as detailed in https://learn.microsoft.com/en-us/azure/ai-studio/tutorials/deploy-copilot-sdk 2.) reasons why ai init exits without creating a json.config
3.)  if there is cli command to configure a SEARCH RESOURCE?
