### ISSUE TITLE
Running 'ai init' and selecting 'New AI Project' fails with Python error

### ISSUE THREAD

**Issue by tarunkhurana1** [Azure/aistudio-copilot-sample#97]
Initialize: New AI Project                 
Subscription: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 
                                           
AZURE AI RESOURCE                          
Name: *** Loading choices ***  WARNING: azure-identity Python wheel not found!
 
      TRY: pip install azure-identity
      SEE: https://pypi.org/project/azure-identity/
 
    ERROR: Python script failed! (exit code=1)
 
   OUTPUT: No module named 'azure'
 
I have executed pip install azure-identity but it doesn't help.

**Comment by wilsonmar** [comment]
I ran into this same problem. The azure-identity package is mentioned in
https://github.com/Azure/aistudio-copilot-sample/blob/main/src/copilot_aisdk/requirements.txt
But I got past it running 
https://github.com/Azure/aistudio-copilot-sample/blob/main/requirements.txt
At the root of the repo run:
```
conda install pip
pip install -r requirements.txt

```

**Comment by luigiw** [comment]
@tarunkhurana1 , thank you for reporting this. I agree with @wilsonmar that the issue seems to be related to python dependencies. Can you confirm if you run `pip install -r requirements.txt` successfully?

**Comment by tarunkhurana1** [comment]
The readme.md under /aistudio-copilot-sample has the following errors:
1. Running $python3 -m venv .venv gives error:
Error: Command '['/afh/code/projects/buildingcopilot-3617f252-c45b-4b3a-8487-633816970215/aistudio-copilot-sample/.venv/bin/python3', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
So I ran $python3 -m venv .venv  --without-pip and it completed successfully

I also ran pip install -r requirements.txt at the root of repository but running ai init gives the same error:
Name: *** Loading choices ***  WARNING: azure-identity Python wheel not found!
                                                                  
      TRY: pip install azure-identity                             
      SEE: https://pypi.org/project/azure-identity/               
                                                                  
    ERROR: Python script failed! (exit code=1)                    
                                                                  
   OUTPUT: No module named 'azure'

**Comment by tarunkhurana1** [comment]
> @tarunkhurana1 , thank you for reporting this. I agree with @wilsonmar that the issue seems to be related to python dependencies. Can you confirm if you run `pip install -r requirements.txt` successfully?

Running pip install -r requirements.txt is successful...Thanks

**Comment by tarunkhurana1** [comment]
> conda install pip

conda install pip gives the error message:

vscode ➜ .../projects/buildingcopilot-3617f252-c45b-4b3a-8487-633816970215/code/aistudio-copilot-sample (main) $ conda install pip
bash: conda: command not found

**Comment by tarunkhurana1** [comment]
If I run at the root, ai init seems to be successful. But Readme.md talks about creating a virtual environment and executing ai init on the environment which obviously doesn't see to work. So one question is which Readme.md should I follow i.e. at the root or aistudio-copilot-sample/Readme.md 

Thanks

**Comment by tarunkhurana1** [comment]
As part of following instructions in aistudio-copilot-sample\Readme.md, when executing the following command:

curl -sL https://aka.ms/InstallAzureAICLIDeb | sudo bash

**sudo: unable to resolve host generative-ai-app-3617f252-c45b-4b3a-8487-633816970215: Name or service not known**
dotnet 8.0.200 is already installed.
Downloading Azure.AI.CLI package...
...
Installing Azure.AI.CLI...
**sudo: unable to resolve host generative-ai-app-3617f252-c45b-4b3a-8487-633816970215: Name or service not known**

I received an 'unable to resolve host ' error but it still went ahead with downloading and installing etc.
