### ISSUE TITLE
Contoso UI Change

### ISSUE THREAD

**Issue by yusufdemirbeigene** [Azure/aistudio-copilot-sample#99]
Hi,
After deploying it from preview mode, I saw contoso logo, which i am not happy for production.

I was wondering how to change the "Contoso" logo "some other image i have" for the front end users?  Would you please procide speciffic instructions on how to update the UI elements like chaning the "Contoso" logo?

Thanks.

**Comment by FabianAltendorfer** [comment]
Hi @yusufdemirbeigene 
I didn't try this myself, but in the Deployment Center in your Azure WebApp in Portal, you can see a linked external Github Repo. Fork this repo, make changes and replace the Repo in the Portal with your own Repo. I would assume this could be a way to change your FrontEnd.

**Comment by yusufdemirbeigene** [comment]
Thanks, i found a way. regards
